spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prenotazioni
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
properties:
hibernate:
format_sql: true
application:
name: prenotazioni-meeting
